os: osx
osx_image: xcode10.2

jobs:
  include:
    - stage: "Tests"
      name: "macOS"
      script:
        - xcodebuild test -workspace TypedNotificationCenter.xcworkspace -scheme TypedNotificationCenter-Package -destination 'platform=OS X,arch=x86_64'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter'

    - name: "tvOS"
      script:
        - xcodebuild test -workspace TypedNotificationCenter.xcworkspace -scheme TypedNotificationCenter-Package -destination 'platform=tvOS Simulator,name=Apple TV 4k,OS=12.2'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter'

    - name: "iOS"
      script:
        - xcodebuild test -workspace TypedNotificationCenter.xcworkspace -scheme TypedNotificationCenter-Package -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter'

    - name: "iOS UI"
      script:
        - xcodebuild test -workspace TypedNotificationCenter.xcworkspace -scheme TNCUITestHostiOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter'

    - name: "Linux"
      os: linux
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift test
