#if !canImport(ObjectiveC)
import XCTest

extension ApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApiTests = [
        ("testDeallocateObserver", testDeallocateObserver),
        ("testInvalidateObserver", testInvalidateObserver),
        ("testNotificationWithDifferentObject", testNotificationWithDifferentObject),
        ("testNotificationWithoutObject", testNotificationWithoutObject),
        ("testNotificationWithSameObject", testNotificationWithSameObject),
        ("testValidityNotificationCenterDeallocated", testValidityNotificationCenterDeallocated),
        ("testValidityRemoved", testValidityRemoved),
        ("testValiditySenderDeallocated", testValiditySenderDeallocated),
    ]
}

extension AsyncApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsyncApiTests = [
        ("testSendingFromDifferentQueue", testSendingFromDifferentQueue),
        ("testSuspendedQueue", testSuspendedQueue),
        ("testSuspendedQueueNilSender", testSuspendedQueueNilSender),
    ]
}

extension BridgedNotificationApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BridgedNotificationApiTests = [
        ("testCrossSendingFromNotificationCenter", testCrossSendingFromNotificationCenter),
        ("testCrossSendingFromTypedNotificationCenter", testCrossSendingFromTypedNotificationCenter),
        ("testInvalidPayload", testInvalidPayload),
        ("testInvalidSender", testInvalidSender),
        ("testSending", testSending),
    ]
}

extension PerformanceTestsPosting {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerformanceTestsPosting = [
        ("testPerformance_apple_1percent", testPerformance_apple_1percent),
        ("testPerformance_apple_20percent", testPerformance_apple_20percent),
        ("testPerformance_apple_all", testPerformance_apple_all),
        ("testPerformance_own_1percent", testPerformance_own_1percent),
        ("testPerformance_own_20percent", testPerformance_own_20percent),
        ("testPerformance_own_all", testPerformance_own_all),
    ]
}

extension PerformanceTestsSubscribing {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerformanceTestsSubscribing = [
        ("testPerformance_apple_100senders", testPerformance_apple_100senders),
        ("testPerformance_apple_2senders", testPerformance_apple_2senders),
        ("testPerformance_apple_nilSenders", testPerformance_apple_nilSenders),
        ("testPerformance_own_100senders", testPerformance_own_100senders),
        ("testPerformance_own_2senders", testPerformance_own_2senders),
        ("testPerformance_own_nilSenders", testPerformance_own_nilSenders),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApiTests.__allTests__ApiTests),
        testCase(AsyncApiTests.__allTests__AsyncApiTests),
        testCase(BridgedNotificationApiTests.__allTests__BridgedNotificationApiTests),
        testCase(PerformanceTestsPosting.__allTests__PerformanceTestsPosting),
        testCase(PerformanceTestsSubscribing.__allTests__PerformanceTestsSubscribing),
    ]
}
#endif
