name: run_tests

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: YOCKOW/Action-setup-swift@master
    - name: Install Swift & Run tests
      run: swift test
      
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: fastlane scan --scheme "TypedNotificationCenter macOS"
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'macos' -F 'macos'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: fastlane scan --scheme "TypedNotificationCenter iOS"
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'ios' -F 'ios'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-tvos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: fastlane scan --scheme "TypedNotificationCenter tvOS"
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'tvos' -F 'tvos'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-ios-ui:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: fastlane scan --scheme "TNC UI Test Host iOS"
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'ios-ui' -F 'ios'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
    
