name: run_tests

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Swift & Run tests
      run: |
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        swift test --enable-code-coverage
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'linux' -F 'linux'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: xcodebuild test -scheme TypedNotificationCenter\ macOS -destination 'platform=OS X,arch=x86_64'
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'macos' -F 'macos'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: xcodebuild test -scheme TypedNotificationCenter\ iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'ios' -F 'ios'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-tvos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: xcodebuild test -scheme TypedNotificationCenter\ tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4k,OS=12.2'
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'tvos' -F 'tvos'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  test-ios-ui:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: xcodebuild test -scheme TNC\ UI\ Test\ Host\ iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'ios-ui' -F 'ios'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
    
